// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: frontend.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InDate        string                 `protobuf:"bytes,1,opt,name=InDate,proto3" json:"InDate,omitempty"`
	OutDate       string                 `protobuf:"bytes,2,opt,name=OutDate,proto3" json:"OutDate,omitempty"`
	Lat           float32                `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,4,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHotelsRequest) Reset() {
	*x = SearchHotelsRequest{}
	mi := &file_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelsRequest) ProtoMessage() {}

func (x *SearchHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelsRequest.ProtoReflect.Descriptor instead.
func (*SearchHotelsRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *SearchHotelsRequest) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *SearchHotelsRequest) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

func (x *SearchHotelsRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *SearchHotelsRequest) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type SearchHotelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Hotel               `protobuf:"bytes,1,rep,name=Profiles,proto3" json:"Profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHotelsResponse) Reset() {
	*x = SearchHotelsResponse{}
	mi := &file_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelsResponse) ProtoMessage() {}

func (x *SearchHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelsResponse.ProtoReflect.Descriptor instead.
func (*SearchHotelsResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHotelsResponse) GetProfiles() []*Hotel {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type StoreHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelId       string                 `protobuf:"bytes,1,opt,name=HotelId,proto3" json:"HotelId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	Rate          int32                  `protobuf:"varint,5,opt,name=Rate,proto3" json:"Rate,omitempty"`
	Capacity      int32                  `protobuf:"varint,6,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
	Info          string                 `protobuf:"bytes,7,opt,name=Info,proto3" json:"Info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHotelRequest) Reset() {
	*x = StoreHotelRequest{}
	mi := &file_frontend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHotelRequest) ProtoMessage() {}

func (x *StoreHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHotelRequest.ProtoReflect.Descriptor instead.
func (*StoreHotelRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{2}
}

func (x *StoreHotelRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *StoreHotelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreHotelRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *StoreHotelRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *StoreHotelRequest) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *StoreHotelRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StoreHotelRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type StoreHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelId       string                 `protobuf:"bytes,1,opt,name=HotelId,proto3" json:"HotelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHotelResponse) Reset() {
	*x = StoreHotelResponse{}
	mi := &file_frontend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHotelResponse) ProtoMessage() {}

func (x *StoreHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHotelResponse.ProtoReflect.Descriptor instead.
func (*StoreHotelResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{3}
}

func (x *StoreHotelResponse) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

type FrontendReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelId       string                 `protobuf:"bytes,1,opt,name=HotelId,proto3" json:"HotelId,omitempty"`
	InDate        string                 `protobuf:"bytes,2,opt,name=InDate,proto3" json:"InDate,omitempty"`
	OutDate       string                 `protobuf:"bytes,3,opt,name=OutDate,proto3" json:"OutDate,omitempty"`
	CustomerName  string                 `protobuf:"bytes,4,opt,name=CustomerName,proto3" json:"CustomerName,omitempty"`
	Number        int32                  `protobuf:"varint,5,opt,name=Number,proto3" json:"Number,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendReservationRequest) Reset() {
	*x = FrontendReservationRequest{}
	mi := &file_frontend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendReservationRequest) ProtoMessage() {}

func (x *FrontendReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendReservationRequest.ProtoReflect.Descriptor instead.
func (*FrontendReservationRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{4}
}

func (x *FrontendReservationRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *FrontendReservationRequest) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *FrontendReservationRequest) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

func (x *FrontendReservationRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *FrontendReservationRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *FrontendReservationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FrontendReservationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type FrontendReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendReservationResponse) Reset() {
	*x = FrontendReservationResponse{}
	mi := &file_frontend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendReservationResponse) ProtoMessage() {}

func (x *FrontendReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendReservationResponse.ProtoReflect.Descriptor instead.
func (*FrontendReservationResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{5}
}

func (x *FrontendReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_frontend_proto protoreflect.FileDescriptor

const file_frontend_proto_rawDesc = "" +
	"\n" +
	"\x0efrontend.proto\x12\bprotobuf\x1a\rprofile.proto\"k\n" +
	"\x13SearchHotelsRequest\x12\x16\n" +
	"\x06InDate\x18\x01 \x01(\tR\x06InDate\x12\x18\n" +
	"\aOutDate\x18\x02 \x01(\tR\aOutDate\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x02R\x03lon\"C\n" +
	"\x14SearchHotelsResponse\x12+\n" +
	"\bProfiles\x18\x01 \x03(\v2\x0f.protobuf.HotelR\bProfiles\"\xb7\x01\n" +
	"\x11StoreHotelRequest\x12\x18\n" +
	"\aHotelId\x18\x01 \x01(\tR\aHotelId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Phone\x18\x03 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bLocation\x18\x04 \x01(\tR\bLocation\x12\x12\n" +
	"\x04Rate\x18\x05 \x01(\x05R\x04Rate\x12\x1a\n" +
	"\bCapacity\x18\x06 \x01(\x05R\bCapacity\x12\x12\n" +
	"\x04Info\x18\a \x01(\tR\x04Info\".\n" +
	"\x12StoreHotelResponse\x12\x18\n" +
	"\aHotelId\x18\x01 \x01(\tR\aHotelId\"\xdc\x01\n" +
	"\x1aFrontendReservationRequest\x12\x18\n" +
	"\aHotelId\x18\x01 \x01(\tR\aHotelId\x12\x16\n" +
	"\x06InDate\x18\x02 \x01(\tR\x06InDate\x12\x18\n" +
	"\aOutDate\x18\x03 \x01(\tR\aOutDate\x12\"\n" +
	"\fCustomerName\x18\x04 \x01(\tR\fCustomerName\x12\x16\n" +
	"\x06Number\x18\x05 \x01(\x05R\x06Number\x12\x1a\n" +
	"\bUsername\x18\x06 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\a \x01(\tR\bPassword\"7\n" +
	"\x1bFrontendReservationResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess2\xc4\x01\n" +
	"\x0fFrontendService\x12M\n" +
	"\fSearchHotels\x12\x1d.protobuf.SearchHotelsRequest\x1a\x1e.protobuf.SearchHotelsResponse\x12b\n" +
	"\x13FrontendReservation\x12$.protobuf.FrontendReservationRequest\x1a%.protobuf.FrontendReservationResponseB$Z\"github.com/farzad1132/rwg/protobufb\x06proto3"

var (
	file_frontend_proto_rawDescOnce sync.Once
	file_frontend_proto_rawDescData []byte
)

func file_frontend_proto_rawDescGZIP() []byte {
	file_frontend_proto_rawDescOnce.Do(func() {
		file_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontend_proto_rawDesc), len(file_frontend_proto_rawDesc)))
	})
	return file_frontend_proto_rawDescData
}

var file_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_frontend_proto_goTypes = []any{
	(*SearchHotelsRequest)(nil),         // 0: protobuf.SearchHotelsRequest
	(*SearchHotelsResponse)(nil),        // 1: protobuf.SearchHotelsResponse
	(*StoreHotelRequest)(nil),           // 2: protobuf.StoreHotelRequest
	(*StoreHotelResponse)(nil),          // 3: protobuf.StoreHotelResponse
	(*FrontendReservationRequest)(nil),  // 4: protobuf.FrontendReservationRequest
	(*FrontendReservationResponse)(nil), // 5: protobuf.FrontendReservationResponse
	(*Hotel)(nil),                       // 6: protobuf.Hotel
}
var file_frontend_proto_depIdxs = []int32{
	6, // 0: protobuf.SearchHotelsResponse.Profiles:type_name -> protobuf.Hotel
	0, // 1: protobuf.FrontendService.SearchHotels:input_type -> protobuf.SearchHotelsRequest
	4, // 2: protobuf.FrontendService.FrontendReservation:input_type -> protobuf.FrontendReservationRequest
	1, // 3: protobuf.FrontendService.SearchHotels:output_type -> protobuf.SearchHotelsResponse
	5, // 4: protobuf.FrontendService.FrontendReservation:output_type -> protobuf.FrontendReservationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_frontend_proto_init() }
func file_frontend_proto_init() {
	if File_frontend_proto != nil {
		return
	}
	file_profile_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontend_proto_rawDesc), len(file_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontend_proto_goTypes,
		DependencyIndexes: file_frontend_proto_depIdxs,
		MessageInfos:      file_frontend_proto_msgTypes,
	}.Build()
	File_frontend_proto = out.File
	file_frontend_proto_goTypes = nil
	file_frontend_proto_depIdxs = nil
}
