// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: rajomonclient.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RajomonClient_SearchHotels_FullMethodName        = "/protobuf.RajomonClient/SearchHotels"
	RajomonClient_FrontendReservation_FullMethodName = "/protobuf.RajomonClient/FrontendReservation"
)

// RajomonClientClient is the client API for RajomonClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RajomonClientClient interface {
	SearchHotels(ctx context.Context, in *SearchHotelsRequest, opts ...grpc.CallOption) (*SearchHotelsResponse, error)
	FrontendReservation(ctx context.Context, in *FrontendReservationRequest, opts ...grpc.CallOption) (*FrontendReservationResponse, error)
}

type rajomonClientClient struct {
	cc grpc.ClientConnInterface
}

func NewRajomonClientClient(cc grpc.ClientConnInterface) RajomonClientClient {
	return &rajomonClientClient{cc}
}

func (c *rajomonClientClient) SearchHotels(ctx context.Context, in *SearchHotelsRequest, opts ...grpc.CallOption) (*SearchHotelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchHotelsResponse)
	err := c.cc.Invoke(ctx, RajomonClient_SearchHotels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rajomonClientClient) FrontendReservation(ctx context.Context, in *FrontendReservationRequest, opts ...grpc.CallOption) (*FrontendReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrontendReservationResponse)
	err := c.cc.Invoke(ctx, RajomonClient_FrontendReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RajomonClientServer is the server API for RajomonClient service.
// All implementations must embed UnimplementedRajomonClientServer
// for forward compatibility.
type RajomonClientServer interface {
	SearchHotels(context.Context, *SearchHotelsRequest) (*SearchHotelsResponse, error)
	FrontendReservation(context.Context, *FrontendReservationRequest) (*FrontendReservationResponse, error)
	mustEmbedUnimplementedRajomonClientServer()
}

// UnimplementedRajomonClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRajomonClientServer struct{}

func (UnimplementedRajomonClientServer) SearchHotels(context.Context, *SearchHotelsRequest) (*SearchHotelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHotels not implemented")
}
func (UnimplementedRajomonClientServer) FrontendReservation(context.Context, *FrontendReservationRequest) (*FrontendReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FrontendReservation not implemented")
}
func (UnimplementedRajomonClientServer) mustEmbedUnimplementedRajomonClientServer() {}
func (UnimplementedRajomonClientServer) testEmbeddedByValue()                       {}

// UnsafeRajomonClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RajomonClientServer will
// result in compilation errors.
type UnsafeRajomonClientServer interface {
	mustEmbedUnimplementedRajomonClientServer()
}

func RegisterRajomonClientServer(s grpc.ServiceRegistrar, srv RajomonClientServer) {
	// If the following call pancis, it indicates UnimplementedRajomonClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RajomonClient_ServiceDesc, srv)
}

func _RajomonClient_SearchHotels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHotelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RajomonClientServer).SearchHotels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RajomonClient_SearchHotels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RajomonClientServer).SearchHotels(ctx, req.(*SearchHotelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RajomonClient_FrontendReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrontendReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RajomonClientServer).FrontendReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RajomonClient_FrontendReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RajomonClientServer).FrontendReservation(ctx, req.(*FrontendReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RajomonClient_ServiceDesc is the grpc.ServiceDesc for RajomonClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RajomonClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.RajomonClient",
	HandlerType: (*RajomonClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchHotels",
			Handler:    _RajomonClient_SearchHotels_Handler,
		},
		{
			MethodName: "FrontendReservation",
			Handler:    _RajomonClient_FrontendReservation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rajomonclient.proto",
}
