// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rajomonclient.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rajomonclient_proto protoreflect.FileDescriptor

const file_rajomonclient_proto_rawDesc = "" +
	"\n" +
	"\x13rajomonclient.proto\x12\bprotobuf\x1a\x0efrontend.proto2\xc2\x01\n" +
	"\rRajomonClient\x12M\n" +
	"\fSearchHotels\x12\x1d.protobuf.SearchHotelsRequest\x1a\x1e.protobuf.SearchHotelsResponse\x12b\n" +
	"\x13FrontendReservation\x12$.protobuf.FrontendReservationRequest\x1a%.protobuf.FrontendReservationResponseB$Z\"github.com/farzad1132/rwg/protobufb\x06proto3"

var file_rajomonclient_proto_goTypes = []any{
	(*SearchHotelsRequest)(nil),         // 0: protobuf.SearchHotelsRequest
	(*FrontendReservationRequest)(nil),  // 1: protobuf.FrontendReservationRequest
	(*SearchHotelsResponse)(nil),        // 2: protobuf.SearchHotelsResponse
	(*FrontendReservationResponse)(nil), // 3: protobuf.FrontendReservationResponse
}
var file_rajomonclient_proto_depIdxs = []int32{
	0, // 0: protobuf.RajomonClient.SearchHotels:input_type -> protobuf.SearchHotelsRequest
	1, // 1: protobuf.RajomonClient.FrontendReservation:input_type -> protobuf.FrontendReservationRequest
	2, // 2: protobuf.RajomonClient.SearchHotels:output_type -> protobuf.SearchHotelsResponse
	3, // 3: protobuf.RajomonClient.FrontendReservation:output_type -> protobuf.FrontendReservationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rajomonclient_proto_init() }
func file_rajomonclient_proto_init() {
	if File_rajomonclient_proto != nil {
		return
	}
	file_frontend_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rajomonclient_proto_rawDesc), len(file_rajomonclient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rajomonclient_proto_goTypes,
		DependencyIndexes: file_rajomonclient_proto_depIdxs,
	}.Build()
	File_rajomonclient_proto = out.File
	file_rajomonclient_proto_goTypes = nil
	file_rajomonclient_proto_depIdxs = nil
}
