// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: testserver.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=Input,proto3" json:"Input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_testserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_testserver_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_testserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_testserver_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_testserver_proto protoreflect.FileDescriptor

const file_testserver_proto_rawDesc = "" +
	"\n" +
	"\x10testserver.proto\x12\bprotobuf\"#\n" +
	"\vTestRequest\x12\x14\n" +
	"\x05Input\x18\x01 \x01(\tR\x05Input\"&\n" +
	"\fTestResponse\x12\x16\n" +
	"\x06Output\x18\x01 \x01(\tR\x06Output2K\n" +
	"\n" +
	"GRPCServer\x12=\n" +
	"\fTestendpoint\x12\x15.protobuf.TestRequest\x1a\x16.protobuf.TestResponseB$Z\"github.com/farzad1132/rwg/protobufb\x06proto3"

var (
	file_testserver_proto_rawDescOnce sync.Once
	file_testserver_proto_rawDescData []byte
)

func file_testserver_proto_rawDescGZIP() []byte {
	file_testserver_proto_rawDescOnce.Do(func() {
		file_testserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testserver_proto_rawDesc), len(file_testserver_proto_rawDesc)))
	})
	return file_testserver_proto_rawDescData
}

var file_testserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testserver_proto_goTypes = []any{
	(*TestRequest)(nil),  // 0: protobuf.TestRequest
	(*TestResponse)(nil), // 1: protobuf.TestResponse
}
var file_testserver_proto_depIdxs = []int32{
	0, // 0: protobuf.GRPCServer.Testendpoint:input_type -> protobuf.TestRequest
	1, // 1: protobuf.GRPCServer.Testendpoint:output_type -> protobuf.TestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testserver_proto_init() }
func file_testserver_proto_init() {
	if File_testserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testserver_proto_rawDesc), len(file_testserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testserver_proto_goTypes,
		DependencyIndexes: file_testserver_proto_depIdxs,
		MessageInfos:      file_testserver_proto_msgTypes,
	}.Build()
	File_testserver_proto = out.File
	file_testserver_proto_goTypes = nil
	file_testserver_proto_depIdxs = nil
}
