// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: testserver.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCServer_Testendpoint_FullMethodName = "/protobuf.GRPCServer/Testendpoint"
)

// GRPCServerClient is the client API for GRPCServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Frontend service definition
type GRPCServerClient interface {
	Testendpoint(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type gRPCServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCServerClient(cc grpc.ClientConnInterface) GRPCServerClient {
	return &gRPCServerClient{cc}
}

func (c *gRPCServerClient) Testendpoint(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, GRPCServer_Testendpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCServerServer is the server API for GRPCServer service.
// All implementations must embed UnimplementedGRPCServerServer
// for forward compatibility.
//
// Frontend service definition
type GRPCServerServer interface {
	Testendpoint(context.Context, *TestRequest) (*TestResponse, error)
	mustEmbedUnimplementedGRPCServerServer()
}

// UnimplementedGRPCServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCServerServer struct{}

func (UnimplementedGRPCServerServer) Testendpoint(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Testendpoint not implemented")
}
func (UnimplementedGRPCServerServer) mustEmbedUnimplementedGRPCServerServer() {}
func (UnimplementedGRPCServerServer) testEmbeddedByValue()                    {}

// UnsafeGRPCServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCServerServer will
// result in compilation errors.
type UnsafeGRPCServerServer interface {
	mustEmbedUnimplementedGRPCServerServer()
}

func RegisterGRPCServerServer(s grpc.ServiceRegistrar, srv GRPCServerServer) {
	// If the following call pancis, it indicates UnimplementedGRPCServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCServer_ServiceDesc, srv)
}

func _GRPCServer_Testendpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServerServer).Testendpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCServer_Testendpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServerServer).Testendpoint(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCServer_ServiceDesc is the grpc.ServiceDesc for GRPCServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.GRPCServer",
	HandlerType: (*GRPCServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Testendpoint",
			Handler:    _GRPCServer_Testendpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testserver.proto",
}
